In [40]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Загружаем данные

In [41]:
train_data_path = 'contest_train.csv'
test_data_path = 'contest_test.csv'

In [42]:
df_train = pd.read_csv(train_data_path, sep=',', header=0)
df_test = pd.read_csv(test_data_path, sep=',', header=0)

Фича FEATURE_256 бинарная, значений 0 больше, чем 1. Заполним NAN-значения этой фичи в тесте нулями

In [43]:
df_test['FEATURE_256'].fillna((0.0), inplace=True)

Фичи FEATURE_238 и FEATURE_239 непрерывные. Заполним NAN-значения этой фичи в тесте средним

In [44]:
df_test['FEATURE_238'].fillna((df_test['FEATURE_238'].mean()), inplace=True)
df_test['FEATURE_239'].fillna((df_test['FEATURE_239'].mean()), inplace=True)

## Удаляем фичи с NAN
Попробуем оценить распределение данных

Выберем все фичи без NAN, которые мы будем ужимать с помощью PCA

In [45]:
not_null_df_train = (df_train.isna().sum() / len(df_train))
not_null_df_train = not_null_df_train[not_null_df_train == 0]

features = list(not_null_df_train.keys())
features.remove('ID')
features.remove('TARGET')

## Разделяем данные на трейн и вал

In [46]:
target_df_train = df_train['TARGET'].copy()

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    df_train.loc[:, features], target_df_train, test_size=0.2, random_state=49)

# Построение модели

## RandomForestClassifier

In [48]:
target_df_train = df_train['TARGET'].copy()

In [49]:
class_weight = {
    0: (target_df_train.value_counts()[1] + target_df_train.value_counts()[2]) / len(target_df_train),
    1: (target_df_train.value_counts()[0] + target_df_train.value_counts()[2]) / len(target_df_train),
    2: (target_df_train.value_counts()[0] + target_df_train.value_counts()[1]) / len(target_df_train),
}

In [50]:
forest = RandomForestClassifier(criterion='gini', max_depth=7, min_samples_split=70, random_state=49,
                                n_estimators=100, n_jobs=8, verbose=2,
                               class_weight=class_weight, max_features=len(X_train.keys()))

In [51]:
forest.fit(X_train, y_train)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.


building tree 1 of 100building tree 2 of 100building tree 3 of 100
building tree 4 of 100

building tree 5 of 100
building tree 6 of 100

building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100building tree 11 of 100

building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100building tree 16 of 100

building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100


[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    3.7s


building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82

[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:   12.1s finished


RandomForestClassifier(bootstrap=True,
            class_weight={0: 0.29154602177725214, 1: 0.7695852534562212, 2: 0.9388687247665266},
            criterion='gini', max_depth=7, max_features=207,
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=70, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=8, oob_score=False, random_state=49,
            verbose=2, warm_start=False)

In [52]:
sorted(forest.feature_importances_)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.7878085744887535e-05,
 4.626194717321925e-05,
 5.041098531207863e-05,
 5.282053481245585e-05,
 5.333606260442709e-05,
 5.529476926220172e-05,
 6.300358007740218e-05,
 6.341219503082039e-05,
 6.48494691871666e-05,
 6.523222544038269e-05,
 7.758650541853164e-05,
 9.333166376626433e-05,
 0.00010836391271570798,
 0.00011615766575486119,
 0.0001292950543974895,
 0.00015258224594147295,
 0.000162069644029623,
 0.0001949614563486259,
 0.0002002758371225916,
 0.00023038621802592835,
 0.00023301511555497977,
 0.00024356247251990895,
 0.00024424013603076066,
 0.00025242375096637154,
 0.0002604396629097936,
 0.0002723899248775067,
 0.0002804323653893109,
 0.00028521733888771156,
 0.0002989818066460582,
 0.0003342544867166093,
 0.0003703280772474312,
 0.00039450869937622334,
 0.0003946725078574284,
 0.0004079289507768076,
 0.00046620263434847396,
 0.000467381806196

In [53]:
predicted_random_forest = forest.predict(X_test)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished


In [54]:
print(classification_report(y_test, predicted_random_forest))
print(confusion_matrix(y_test, predicted_random_forest))

              precision    recall  f1-score   support

           0       0.80      0.70      0.75      3427
           1       0.34      0.47      0.40      1150
           2       0.42      0.45      0.43       328

   micro avg       0.63      0.63      0.63      4905
   macro avg       0.52      0.54      0.53      4905
weighted avg       0.67      0.63      0.65      4905

[[2409  898  120]
 [ 533  535   82]
 [  63  118  147]]


## DecisionTreeClassifier

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
tree = DecisionTreeClassifier(splitter='best', random_state=49, class_weight=class_weight, max_depth=50)

In [57]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight={0: 0.29154602177725214, 1: 0.7695852534562212, 2: 0.9388687247665266},
            criterion='gini', max_depth=50, max_features=None,
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=49, splitter='best')

In [58]:
sorted(tree.feature_importances_)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00010551557647025477,
 0.00010816804443728179,
 0.00010862708635737287,
 0.00011083597054750485,
 0.0001539357290402814,
 0.000252587145201391,
 0.0002655123697827427,
 0.00027203425191593434,
 0.0003001510464193205,
 0.0003198282811045312,
 0.00034099080621086163,
 0.00036170227280948603,
 0.0003776592958769698,
 0.0003810754626962264,
 0.0003983109658419445,
 0.00045295337819897965,
 0.0004698121833427916,
 0.0004952298301337397,
 0.0005726700123750129,
 0.0005947443679573459,
 0.000602581647824829,
 0.0006098048526881957,
 0.0006518812371397239,
 0.0006607012877509806,
 0.0007123843389933246,
 0.0007175194464184875,
 0.0007660585435157533,
 0.0007925531741285215,
 0.0007970091303429682,
 0.0008664033911754805,
 0.0009864828325391345,
 0.0010377718894743844,
 0.00109650508640352,
 0.0011418673513370252,
 0.001156487665279323,
 0.0012074788546427605,
 0.0012

In [59]:
predicted_tree = tree.predict(X_test)

In [60]:
print(classification_report(y_test, predicted_tree))
print(confusion_matrix(y_test, predicted_tree))

              precision    recall  f1-score   support

           0       0.73      0.74      0.73      3427
           1       0.27      0.27      0.27      1150
           2       0.28      0.25      0.27       328

   micro avg       0.59      0.59      0.59      4905
   macro avg       0.43      0.42      0.42      4905
weighted avg       0.59      0.59      0.59      4905

[[2520  772  135]
 [ 763  313   74]
 [ 161   84   83]]


## xgboost

In [61]:
import xgboost as xgb

In [62]:
df_target_xgb = y_train.copy()
df_target_xgb[df_target_xgb == 0] = class_weight[0] * 10
df_target_xgb[df_target_xgb == 1] = class_weight[1]
df_target_xgb[df_target_xgb == 2] = class_weight[2]

In [63]:
xgboost_model = xgb.XGBClassifier(n_estimators=100, verbosity=2, random_state=49, n_jobs=8, 
                                  num_class=3, objective='multi:softmax', weights=df_target_xgb)

In [64]:
xgboost_model.fit(X_train, y_train)

[18:50:20] WARNING: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/learner.cc:516: 
Parameters: { weights } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[18:50:20] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 122 extra nodes, 0 pruned nodes, max_depth=6
[18:50:20] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 104 extra nodes, 0 pruned nodes, max_depth=6
[18:50:21] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 118 extra nodes, 0 pruned nodes, max_depth=6
[18:50:21] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_6

[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 70 extra nodes, 0 pruned nodes, max_depth=6
[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 90 extra nodes, 0 pruned nodes, max_depth=6
[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 114 extra nodes, 0 pruned nodes, max_depth=6
[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 60 extra nodes, 0 pruned nodes, max_depth=6
[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 58 extra nodes, 0 pruned nodes, max_depth=6
[18:50:22] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.c

[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 120 extra nodes, 0 pruned nodes, max_depth=6
[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 62 extra nodes, 0 pruned nodes, max_depth=6
[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 94 extra nodes, 0 pruned nodes, max_depth=6
[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 112 extra nodes, 0 pruned nodes, max_depth=6
[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 42 extra nodes, 0 pruned nodes, max_depth=6
[18:50:24] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.

[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 116 extra nodes, 0 pruned nodes, max_depth=6
[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 112 extra nodes, 0 pruned nodes, max_depth=6
[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 64 extra nodes, 0 pruned nodes, max_depth=6
[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 54 extra nodes, 0 pruned nodes, max_depth=6
[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 62 extra nodes, 0 pruned nodes, max_depth=6
[18:50:26] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.

[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 36 extra nodes, 0 pruned nodes, max_depth=6
[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 68 extra nodes, 0 pruned nodes, max_depth=6
[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 78 extra nodes, 0 pruned nodes, max_depth=6
[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 70 extra nodes, 0 pruned nodes, max_depth=6
[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 76 extra nodes, 0 pruned nodes, max_depth=6
[18:50:27] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc

[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 80 extra nodes, 0 pruned nodes, max_depth=6
[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 100 extra nodes, 0 pruned nodes, max_depth=6
[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 102 extra nodes, 0 pruned nodes, max_depth=6
[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 56 extra nodes, 0 pruned nodes, max_depth=6
[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 122 extra nodes, 0 pruned nodes, max_depth=6
[18:50:29] INFO: /tmp/pip-build-z1hftoo5/xgboost/build/temp.linux-x86_64-3.6/xgboost/src/tree/updater_prune

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=8, num_class=3, num_parallel_tree=1,
       objective='multi:softprob', random_state=49, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1,
       tree_method='exact', validate_parameters=1, verbosity=2,
       weights=21816    2.915460
4411     2.915460
20148    0.769585
24193    2.915460
10725    2.915460
           ...
7924     2.915460
19638    2.915460
15861    0.769585
22189    2.915460
426      2.915460
Name: TARGET, Length: 19616, dtype: float64)

In [65]:
predicted_xgboost_model = xgboost_model.predict(X_test)

In [66]:
print(classification_report(y_test, predicted_xgboost_model))
print(confusion_matrix(y_test, predicted_xgboost_model))

              precision    recall  f1-score   support

           0       0.74      0.95      0.83      3427
           1       0.44      0.12      0.19      1150
           2       0.56      0.27      0.37       328

   micro avg       0.71      0.71      0.71      4905
   macro avg       0.58      0.45      0.46      4905
weighted avg       0.66      0.71      0.65      4905

[[3270  119   38]
 [ 976  142   32]
 [ 178   60   90]]


In [67]:
print(xgboost_model.feature_importances_)

[0.00408885 0.00445734 0.00300565 0.         0.00308198 0.
 0.00221464 0.00392834 0.00377567 0.         0.00256525 0.00434492
 0.00323049 0.00210145 0.00562976 0.00210327 0.002102   0.003079
 0.         0.00409362 0.00463549 0.00399651 0.00339199 0.00266312
 0.00422541 0.         0.         0.00268108 0.         0.
 0.         0.00429978 0.00415731 0.0042132  0.00464761 0.00384633
 0.00393027 0.00290455 0.00480852 0.00524203 0.00315158 0.00482863
 0.0058268  0.00397182 0.00404294 0.00422082 0.00439453 0.00467725
 0.00498851 0.00442501 0.00461675 0.0038933  0.00323444 0.00516183
 0.00444926 0.00449283 0.00455353 0.00411648 0.00435865 0.00427414
 0.00365913 0.0050997  0.00411433 0.00448241 0.00418433 0.00423089
 0.0041083  0.00855628 0.01347866 0.00490483 0.         0.01332924
 0.0053563  0.00408119 0.0038288  0.01783529 0.0076694  0.0049893
 0.00428409 0.00421189 0.00434302 0.00430705 0.00425025 0.00476688
 0.00424575 0.00431427 0.00454705 0.004901   0.00443175 0.00399286
 0.00356682 0.

## catboost

In [68]:
import catboost

In [69]:
catboost_model = catboost.CatBoostClassifier(
    iterations=100, task_type="GPU", devices='0', loss_function='MultiClass', learning_rate=0.1,
    eval_metric='TotalF1', random_seed=49, class_weights=class_weight)

In [70]:
catboost_model.fit(X_train, y_train)

0:	learn: 0.5387069	total: 10.2ms	remaining: 1.01s
1:	learn: 0.5449262	total: 18.1ms	remaining: 888ms
2:	learn: 0.5444691	total: 23.5ms	remaining: 759ms
3:	learn: 0.5464456	total: 28.6ms	remaining: 686ms
4:	learn: 0.5489898	total: 33.7ms	remaining: 640ms
5:	learn: 0.5519441	total: 39ms	remaining: 611ms
6:	learn: 0.5550676	total: 44.4ms	remaining: 590ms
7:	learn: 0.5537811	total: 49.4ms	remaining: 568ms
8:	learn: 0.5516919	total: 54.7ms	remaining: 553ms
9:	learn: 0.5542058	total: 59.7ms	remaining: 538ms
10:	learn: 0.5578696	total: 65.1ms	remaining: 527ms
11:	learn: 0.5630961	total: 70.3ms	remaining: 516ms
12:	learn: 0.5619048	total: 75.3ms	remaining: 504ms
13:	learn: 0.5613036	total: 80.5ms	remaining: 495ms


14:	learn: 0.5641845	total: 85.5ms	remaining: 485ms
15:	learn: 0.5662632	total: 90.7ms	remaining: 476ms
16:	learn: 0.5651919	total: 95.8ms	remaining: 468ms
17:	learn: 0.5668396	total: 101ms	remaining: 459ms
18:	learn: 0.5684757	total: 106ms	remaining: 450ms
19:	learn: 0.5702964	total: 111ms	remaining: 443ms
20:	learn: 0.5726342	total: 116ms	remaining: 436ms
21:	learn: 0.5732094	total: 121ms	remaining: 429ms
22:	learn: 0.5726521	total: 126ms	remaining: 423ms
23:	learn: 0.5729043	total: 131ms	remaining: 415ms
24:	learn: 0.5734260	total: 136ms	remaining: 409ms
25:	learn: 0.5751468	total: 141ms	remaining: 402ms
26:	learn: 0.5773443	total: 146ms	remaining: 396ms
27:	learn: 0.5786908	total: 152ms	remaining: 390ms
28:	learn: 0.5794262	total: 157ms	remaining: 384ms
29:	learn: 0.5802121	total: 162ms	remaining: 378ms
30:	learn: 0.5798281	total: 167ms	remaining: 371ms
31:	learn: 0.5810775	total: 171ms	remaining: 364ms
32:	learn: 0.5811342	total: 176ms	remaining: 358ms
33:	learn: 0.5813479	total: 

In [71]:
predicted_catboost_model = catboost_model.predict(X_test)

In [72]:
print(classification_report(y_test, predicted_catboost_model))
print(confusion_matrix(y_test, predicted_catboost_model))

              precision    recall  f1-score   support

           0       0.81      0.74      0.77      3427
           1       0.37      0.46      0.41      1150
           2       0.47      0.47      0.47       328

   micro avg       0.66      0.66      0.66      4905
   macro avg       0.55      0.56      0.55      4905
weighted avg       0.68      0.66      0.67      4905

[[2539  788  100]
 [ 551  527   72]
 [  55  120  153]]
